<?php

return [
    'Akurai Theme' => [
        'url' => 'docs/akurai',
        'children' => [
            'Installation' => 'docs/akurai/installation',
            'Theme Registration' => 'docs/akurai/registration',
            'Review Page Slug' => 'docs/akurai/setting-review-page-slug',
            'Creating Review Pages' => 'docs/akurai/creating-review-pages',
            'Review Page Templates' => 'docs/akurai/review-page-templates',
            'Review Page Blocks' => 'docs/akurai/review-page-blocks',
            'Page Templates' => 'docs/akurai/page-templates',
            'Blocks & Shortcodes' => 'docs/akurai/blocks-shortcodes',
            'Widget Areas' => 'docs/akurai/widget-areas',
            'Widgets' => 'docs/akurai/widgets',
            'Breadcrumbs' => 'docs/akurai/breadcrumbs',
            'Theme Customizations' => 'docs/akurai/customizations',
            'AMP Support' => 'docs/akurai/amp',
            'Demo Import' => 'docs/akurai/demo-import',
            'Theme Updates' => 'docs/akurai/updates',
            'Child Theme' => 'docs/akurai/child-theme',
            'How To ...' => 'docs/akurai/how-to',
        ],
    ],
    'Spinoko Theme' => [
        'url' => 'docs/spinoko',
        'children' => [
            'Installation' => 'docs/spinoko/installation',
            'Theme Registration' => 'docs/spinoko/registration',
            'Casino Page Slug' => 'docs/spinoko/setting-casino-page-slug',
            'Creating Casino Pages' => 'docs/spinoko/creating-casino-pages',
            'Casino Page Blocks' => 'docs/spinoko/casino-page-blocks',
            'Casino Page Templates' => 'docs/spinoko/casino-page-templates',
            'Game Page Slug' => 'docs/spinoko/setting-game-page-slug',
            'Creating Game Pages' => 'docs/spinoko/creating-game-pages',
            'Game Page Templates' => 'docs/spinoko/game-page-templates',
            'Demo Games' => 'docs/spinoko/demo-games',
            'Theme Blocks' => 'docs/spinoko/blocks',
            'Page Templates' => 'docs/spinoko/page-templates',
            'Widgets' => 'docs/spinoko/widgets',
            'Theme Customizations' => 'docs/spinoko/customizations',
            'Navigation Menus' => 'docs/spinoko/navigation',
            'Header Notifications' => 'docs/spinoko/notifications',
            'AMP Support' => 'docs/spinoko/amp',
            'Translating Spinoko' => 'docs/spinoko/translation',
            'Demo Import' => 'docs/spinoko/demo-import',
            'Theme Updates' => 'docs/spinoko/updates',
            'Child Theme' => 'docs/spinoko/child-theme',
            'How To ...' => 'docs/spinoko/how-to',
        ],
    ],
    'Sikika Theme' => [
        'url' => 'docs/sikika',
        'children' => [
            'Installation' => 'docs/sikika/installation',
            'Page Templates' => 'docs/sikika/page-templates',
            'Widget Areas' => 'docs/sikika/widget-areas',
            'Theme Customizations' => 'docs/sikika/customizations',
            'Banners' => 'docs/sikika/banners',
            'AMP Support' => 'docs/sikika/amp',
            'Theme Updates' => 'docs/sikika/updates',
            'Child Theme' => 'docs/sikika/child-theme',
        ],
    ],
    'Kemoku Plugin' => [
        'url' => 'docs/kemoku',
        'children' => [
            'Installation' => 'docs/kemoku/installation',
            'Plugin Registration' => 'docs/kemoku/registration',
            'Review Page Slug' => '/docs/kemoku/registration#set-reviews-page-slug',
            'Review Pages' => 'docs/kemoku/review-pages',
            'Review Page Blocks' => 'docs/kemoku/review-page-blocks',
            'Blocks' => 'docs/kemoku/blocks',
            'Shortcodes' => 'docs/kemoku/shortcodes',
            'Widgets' => 'docs/kemoku/widgets',
            'Settings' => 'docs/kemoku/settings',
            'Listing Tools' => 'docs/kemoku/listing-tools',
            'How To ...' => 'docs/kemoku/how-to',
            'Plugin Updates' => 'docs/kemoku/plugin-updates',
        ],
    ],
    //    'Sibet Plugin' => [
    //        'url' => 'docs/sibet',
    //        'children' => [
    //            'Installation' => 'docs/sibet/installation',
    //            'Plugin Setup' => 'docs/sibet/plugin-setup',
    //            'Plugin Settings' => 'docs/sibet/plugin-settings',
    //            'Plugin Shortcodes' => 'docs/sibet/plugin-shortcodes',
    //            'Affiliate Settings' => 'docs/sibet/bookmaker-settings',
    //            'Feed Updates' => 'docs/sibet/feed-updates',
    //            'Customizing Styles' => 'docs/sibet/custom-css',
    //            'Plugin Updates' => 'docs/sibet/plugin-updates',
    //        ],
    //    ],
    'DinOdds Plugin' => [
        'url' => 'docs/dinodds',
        'children' => [
            'DinoFeeds API' => 'docs/dinodds/api',
            'Installation' => 'docs/dinodds/installation',
            'Plugin Setup' => 'docs/dinodds/plugin-setup',
            'Plugin Settings' => 'docs/dinodds/plugin-settings',
            'Plugin Shortcodes' => 'docs/dinodds/plugin-shortcodes',
            'Affiliate Settings' => 'docs/dinodds/affiliate-settings',
            'Feed Updates' => 'docs/dinodds/feed-updates',
            'Scheduling' => 'docs/dinodds/scheduling',
            'Changing Colors' => 'docs/dinodds/colors',
            'Plugin Updates' => 'docs/dinodds/plugin-updates',
        ],
    ],
    'AkuraiGeo Plugin' => [
        'url' => 'docs/akurai-geo',
        'children' => [
            'Installation' => 'docs/akurai-geo/installation',
            'Settings' => 'docs/akurai-geo/settings',
            'Blocks' => 'docs/akurai-geo/blocks',
            'Review Fields' => 'docs/akurai-geo/review-fields',
            'Cloudflare' => 'docs/akurai-geo/cloudflare',
            'Plugin Updates' => 'docs/akurai-geo/plugin-updates',
        ],
    ],
    'SpinokoGeo Plugin' => [
        'url' => 'docs/spinoko-geo',
        'children' => [
            'Installation' => 'docs/spinoko-geo/installation',
            'Settings' => 'docs/spinoko-geo/settings',
            'Blocks' => 'docs/spinoko-geo/blocks',
            'Cloudflare' => 'docs/spinoko-geo/cloudflare',
            'Plugin Updates' => 'docs/spinoko-geo/plugin-updates',
        ],
    ],
    'Nonaki Plugin' => [
        'url' => 'docs/nonaki',
        'children' => [
            'Installation' => 'docs/nonaki/installation',
            'Using The Plugin' => 'docs/nonaki/using-plugin',
            'Plugin Updates' => 'docs/nonaki/plugin-updates',
        ],
    ],
    'Hello Cookie Plugin' => [
        'url' => 'docs/hello-cookie',
        'children' => [
            'Installation' => 'docs/hello-cookie/installation',
            'Using The Plugin' => 'docs/hello-cookie/using-plugin',
            'Plugin Updates' => 'docs/hello-cookie/plugin-updates',
        ],
    ],
];
